### ISSUE TITLE
Feature request: functions to edit .emacs-profiles.el

### ISSUE THREAD

**Issue by guraltsev** [plexus/chemacs#35]
It would be useful to have a function/macro that would allow programmatically adding things to `~/.emacs-profiles.el` from elisp.

EDIT: changed phrasing of the feature request. Initial wording could seem very rude. Apologies.

**Comment by plexus** [comment]
Hi @guraltsev ,

This is probably well intentioned, but please think twice in the future before posting something like this. Just because someone has made something and made it available to you for free does not mean you get to ask them to work for you for free.

**Comment by guraltsev** [comment]
Hello @plexus,

I am sorry. Often projects hosted on github have a tag called "wishilst" or "feature request" in the issue tracker. By posting this here I did not want to incite you to work on it (rereading my initial phrasing I realize now that the tone seemed inappropriate).

I use this package in my setup and I wanted to give feedback on how I believe it could be improved (the point of a feature request/wishlist), at least for my use case. 

I was expecting as a response one of the following:
1) pointer to that being implemented but undocumented
2) feedback on why this is not a good idea
3) acknowledgement that that could be a good idea
4) a phrase along the lines of "pull requests welcome"
5) an offer to implement it

I was by no means expecting the latter. I am once again extremely apologetic that I phrased it that way. 

Given this, do you have opinions about 2-3) is it a good idea / are there caveats? If not I may try to submit a pull request. I am trying to learn elisp a bit and for practice I have been recently trying to contribute small bugfixes that I am able to do to elisp projects (I did a couple small ones to doom-emacs). As a matter of fact that is why I use chemacs: to launch a bunch of different profiles to test out fixing bugs.

**Comment by plexus** [comment]
In general I would say "PR welcome", chemacs has had a lot of small contributions in the past that all together have amounted to significant improvements. However for this kind of functionality I think it would make more sense to have it as a separate project, since it would be library code (code that other people consume), rather than the "bootloader" that chemacs currently is.

For instance when you add this it would make sense to have it on MELPA (or similar). Chemacs is not on MELPA. I'd also prefer not to put it on MELPA because it's a painful process.
